### ISSUE TITLE
Problem with Mqtt Connected

### ISSUE THREAD

**Issue by Stephan-87** [NickStallman/home-assistant-repo#3]
Hay 
I have followed the instructions provided to install addon but with no luck to work i thank its with mqtt i have user and password for mqtt MQTT broker configured already and work with may Zigbee2MQTT and devices 

Not clear The MQTT URL is in the format of mqtt://<username>:<password>@<host> 

can you please photo added or your setup example 

Log 

s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

> cli
> node build/src/index.js

2024-05-24 08:11:22 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:22 info: Fetched l18n properties. 
2024-05-24 08:11:22 error: Invalid connect message: {
  data: {
    result_code: 1,
    result_msg: 'success',
    result_data: {
      service: 'connect',
      token: '725cde8d-bf08-42d6-9f9a-46ea3d421363',
      uid: 1,
      tips_disable: 0
    }
  },
  [Symbol(level)]: 'error',
  [Symbol(splat)]: [ { data: [Object] } ]
}
2024-05-24 08:11:23 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:24 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:25 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:26 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:27 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:28 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:29 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:30 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:31 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 08:11:32 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
/usr/src/app/build/src/winetHandler.js:343
            this.currentDevice = this.devices[0].dev_id;
                                                 ^

TypeError: Cannot read properties of undefined (reading 'dev_id')
    at winetHandler.scanDevices (/usr/src/app/build/src/winetHandler.js:343:50)
    at Timeout._onTimeout (/usr/src/app/build/src/winetHandler.js:95:22)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.12.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

> cli
> node build/src/index.js

2024-05-24 08:12:22 info: Connected to MQTT broker 
2024-05-24 08:12:22 info: Fetched l18n properties. 
2024-05-24 08:12:22 error: Invalid connect message: {
  data: {
    result_code: 1,
    result_msg: 'success',
    result_data: {
      service: 'connect',
      token: '725cde8d-bf08-42d6-9f9a-46ea3d421363',
      uid: 1,
      tips_disable: 0
    }
  },
  [Symbol(level)]: 'error',
  [Symbol(splat)]: [ { data: [Object] } ]
}
/usr/src/app/build/src/winetHandler.js:343
            this.currentDevice = this.devices[0].dev_id;
                                                 ^

TypeError: Cannot read properties of undefined (reading 'dev_id')
    at winetHandler.scanDevices (/usr/src/app/build/src/winetHandler.js:343:50)
    at Timeout._onTimeout (/usr/src/app/build/src/winetHandler.js:95:22)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.12.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Stephan-87** [comment]
My Options : 

winet_host: 192.168.68.104
mqtt_url: mqtt://mqtt-manuel:patil@192.168.68.147:1883
winet_user: ""
winet_pass: ""
poll_interval: 10

**Comment by macduff89** [comment]
Hi, I’m trying this with a SG8.0RS and getting same results as @Stephan-87. Not very experienced with MQTT but I did install Mosquitto to use GoSungrow and didn’t have any issues.

My config (tried Winet admin user to see if it would make a difference):

winet_host: 192.168.0.109
mqtt_url: mqtt://mqtt_user:mqtt_pw@127.0.0.1
winet_user: admin
winet_pass: pw8888
poll_interval: 10

Log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

> cli
> node build/src/index.js

2024-05-24 21:58:27 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 21:58:27 info: Fetched l18n properties. 
2024-05-24 21:58:28 error: Invalid connect message: {
  data: {
    result_code: 1,
    result_msg: 'success',
    result_data: {
      service: 'connect',
      token: '37ffe725-2d93-44fe-af47-405786d2ad6a',
      uid: 1,
      tips_disable: 0
    }
  },
  [Symbol(level)]: 'error',
  [Symbol(splat)]: [ { data: [Object] } ]
}
2024-05-24 21:58:28 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 21:58:29 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 21:58:30 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 21:58:31 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 21:58:32 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 21:58:33 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 21:58:34 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 21:58:35 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883
2024-05-24 21:58:36 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
2024-05-24 21:58:37 error: MQTT error: Error: connect ECONNREFUSED 127.0.0.1:1883 
/usr/src/app/build/src/winetHandler.js:343
            this.currentDevice = this.devices[0].dev_id;
                                                 ^

TypeError: Cannot read properties of undefined (reading 'dev_id')
    at winetHandler.scanDevices (/usr/src/app/build/src/winetHandler.js:343:50)
    at Timeout._onTimeout (/usr/src/app/build/src/winetHandler.js:95:22)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.12.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping

**Comment by NickStallman** [comment]
The top part of your log says it's trying to connect to MQTT via localhost, not 192.168.68.147.
Might that log be a old log before you added the correct MQTT IP in?

Then from 2024-05-24 08:12:22 it says it is connecting to MQTT without complaining.
The actual error is "Invalid connect message".

Have you updated the firmware on your Winet dongle at any point? Maybe try upgrading that.
It looks like the connect message comes from a older firmware than what I've tested it on.
You will know when you are on the latest version when going to the Winet's IP it will force you to change the default password, and it gives you a login screen rather than letting you in to the dongle without logging in.

**Comment by macduff89** [comment]
Sorry - didn't click before that I have a WiNet-S, not WiNet-S2. I guess this won't work for me but still baffled why it can't connect to Mosquitto.

**Comment by NickStallman** [comment]
I think that MQTT error might be older, before you applied the config since what you pasted is multiple runs of it, and the last one connected to MQTT just fine.

I'm actually curious to see what the older Winet-S does, as it also has a Websocket API. It doesn't seem totally incompatible from what I've seen.

Could you collect a HAR file of you navigating to your Winet-S and viewing the pages showing the stats?
https://help.okta.com/oag/en-us/content/topics/access-gateway/troubleshooting-with-har.htm
You'll want to open dev tools, Preserve Log then do a full reload of the page. Then navigate all the page showing inverter/battery info.
The HAR file will contain the full trace of the Websocket communication and I can see if it's possible to make it compatible or not.

**Comment by macduff89** [comment]
[winet-s.har.txt](https://github.com/NickStallman/home-assistant-repo/files/15445135/winet-s.har.txt)

![winet-s](https://github.com/NickStallman/home-assistant-repo/assets/168157580/12b7d322-4694-4cd7-abd7-0193126ccfff)

Here's the har file, including navigating to Device Monitoring. Didn't need to login to show this. Unfortunately this doesn't seem to show any load measurements.

Btw, I'm not the OP, I never got a "Connected to MQTT broker" message in my log. I'll have another look today and see if I can get anywhere.

**Comment by NickStallman** [comment]
Thanks @macduff89 it looks like the older dongles are actually virtually identical, at least for this websocket protocol.
I've just pushed 0.1.5 which just tweaks the protocol handling slightly which might mean it might work perfectly now. :)

As for your MQTT, your url is mqtt://mqtt_user:mqtt_pw@127.0.0.1 but it seems your MQTT server is not at 127.0.0.1:1883. Remember this runs inside of docker which is possibly what's causing that issue since it virtualizes the network. Try using the local LAN IP in your MQTT url instead.

**Comment by macduff89** [comment]
Thanks, that makes sense. Successfully connecting to mqtt server now but still not getting data after the update.

Here's the log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

> cli
> node build/src/index.js

2024-05-25 23:19:57 info: Connected to MQTT broker 
2024-05-25 23:19:57 info: Fetched l18n properties. 
2024-05-25 23:19:57 info: Running an older firmware version 
2024-05-25 23:19:57 info: Connected to Winet, logging in 
2024-05-25 23:19:57 info: Authenticated successfully 
2024-05-25 23:19:57 error: Invalid devicelist message: {
  data: {
    result_code: 1,
    result_msg: 'success',
    result_data: { service: 'devicelist', list: [Array], count: 1 }
  },
  [Symbol(level)]: 'error',
  [Symbol(splat)]: [ { data: [Object] } ]
}
/usr/src/app/build/src/winetHandler.js:343
            this.currentDevice = this.devices[0].dev_id;
                                                 ^

TypeError: Cannot read properties of undefined (reading 'dev_id')
    at winetHandler.scanDevices (/usr/src/app/build/src/winetHandler.js:343:50)
    at Timeout._onTimeout (/usr/src/app/build/src/winetHandler.js:95:22)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.12.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by NickStallman** [comment]
Cool that's a good sign, but there must be a couple more small variations. I'll do a little bit more of a comparison and let you know what I find.

**Comment by Stephan-87** [comment]
Hi the MQTT  Successfully connecting  but as macduff89


> cli
> node build/src/index.js

2024-05-26 14:49:13 info: Connected to MQTT broker 
2024-05-26 14:49:13 info: Fetched l18n properties. 
2024-05-26 14:49:13 info: Running an older firmware version 
2024-05-26 14:49:13 info: Connected to Winet, logging in 
2024-05-26 14:49:13 info: Authenticated successfully 
2024-05-26 14:49:13 error: Invalid devicelist message: {
  data: {
    result_code: 1,
    result_msg: 'success',
    result_data: { service: 'devicelist', list: [Array], count: 2 }
  },
  [Symbol(level)]: 'error',
  [Symbol(splat)]: [ { data: [Object] } ]
}
/usr/src/app/build/src/winetHandler.js:343
            this.currentDevice = this.devices[0].dev_id;
                                                 ^

TypeError: Cannot read properties of undefined (reading 'dev_id')
    at winetHandler.scanDevices (/usr/src/app/build/src/winetHandler.js:343:50)
    at Timeout._onTimeout (/usr/src/app/build/src/winetHandler.js:95:22)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.12.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by NickStallman** [comment]
I've just released version 0.1.6 which should now be able to parse the older Winet-S device list better.
I've given all the other commands a once over as well to try and ensure they are also compatible.

Let me know how you go.

**Comment by Stephan-87** [comment]
> I've just released version 0.1.6 which should now be able to parse the older Winet-S device list better. I've given all the other commands a once over as well to try and ensure they are also compatible.
> 
> Let me know how you go.

Hi
i don't see any update with released version 0.1.6 in Home Assistant

**Comment by NickStallman** [comment]
You might need to go Addons -> Addon Store -> top right 3 dots -> Check for updates. That will pick it up faster.

**Comment by macduff89** [comment]
Looks good!

```
2024-05-29 09:32:48 info: Connected to MQTT broker 
2024-05-29 09:32:58 info: Fetched l18n properties. 
2024-05-29 09:32:58 info: Connected to a older Winet-S device 
2024-05-29 09:32:58 info: Connected to Winet, logging in 
2024-05-29 09:32:59 info: Authenticated successfully 
2024-05-29 09:32:59 info: Detected device: SG8.0RS (A2360814641) 
2024-05-29 09:32:59 info: Registered device: SG8.0RS_A2360814641 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_ongrid_running_time 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 daily_yield 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_yield 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 running_status 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 bus_voltage 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 internal_air_temperature 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 array_insulation_resistance 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_dc_power 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_active_power 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_reactive_power 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_apparent_power 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_power_factor 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 grid_frequency 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 phase_a_voltage 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 phase_a_current 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 number_of_afci_faults 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 maximum_apparent_power 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt1_voltage 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt1_current 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt1_power 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt2_voltage 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt2_current 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt2_power 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt3_voltage 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt3_current 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt3_power 
2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt_total_power 
2024-05-29 09:32:59 info: Configured 27 sensors 
2024-05-29 09:32:59 info: Updated 27 sensors 
```

**Comment by Stephan-87** [comment]
> You might need to go Addons -> Addon Store -> top right 3 dots -> Check for updates. That will pick it up faster.

Thanks i will test that

**Comment by cmadds** [comment]
> Looks good!
> 
> ```
> 2024-05-29 09:32:48 info: Connected to MQTT broker 
> 2024-05-29 09:32:58 info: Fetched l18n properties. 
> 2024-05-29 09:32:58 info: Connected to a older Winet-S device 
> 2024-05-29 09:32:58 info: Connected to Winet, logging in 
> 2024-05-29 09:32:59 info: Authenticated successfully 
> 2024-05-29 09:32:59 info: Detected device: SG8.0RS (A2360814641) 
> 2024-05-29 09:32:59 info: Registered device: SG8.0RS_A2360814641 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_ongrid_running_time 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 daily_yield 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_yield 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 running_status 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 bus_voltage 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 internal_air_temperature 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 array_insulation_resistance 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_dc_power 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_active_power 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_reactive_power 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_apparent_power 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 total_power_factor 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 grid_frequency 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 phase_a_voltage 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 phase_a_current 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 number_of_afci_faults 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 maximum_apparent_power 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt1_voltage 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt1_current 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt1_power 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt2_voltage 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt2_current 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt2_power 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt3_voltage 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt3_current 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt3_power 
> 2024-05-29 09:32:59 info: Configured sensor: SG8.0RS_A2360814641 mppt_total_power 
> 2024-05-29 09:32:59 info: Configured 27 sensors 
> 2024-05-29 09:32:59 info: Updated 27 sensors 
> ```

Hey @macduff89 - were you able to get your sensors into MQTT? I am getting the following:

`Received message on illegal discovery topic 'homeassistant/sensor/SG8.0RT_A2372803212/i18n_common_group_bunch_title_andpercent3_power/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/integrations/mqtt/#discovery-topic`

**Comment by NickStallman** [comment]
Ah it's probably the full stop in the inverter name which is causing an issue. I'll release a new version tomorrow morning to strip that out. I've got a SH10RS so no full stop.

**Comment by macduff89** [comment]
@cmadds is that error in mosquitto? I haven’t seen one like it but entities have not been auto-discovering. Was trying to figure out what else I was doing wrong.

**Comment by NickStallman** [comment]
Give 0.1.7 a go. I've added filtering to the model name so MQTT will be happy.

**Comment by cmadds** [comment]
> Ah it's probably the full stop in the inverter name which is causing an issue. I'll release a new version tomorrow morning to strip that out. I've got a SH10RS so no full stop.

Yeah thats exactly the issue @NickStallman - thanks for replying so quick. I tried to use Slugify in the code to remove the '.' -  but my skills arent quite there yet. Every restart would remove the code.

**Comment by macduff89** [comment]
Awesome that’s working now! If only the inverter passed on consumption meter values it would be perfect.

**Comment by cmadds** [comment]
> Give 0.1.7 a go. I've added filtering to the model name so MQTT will be happy.

Thanks so much @NickStallman - works like a charm.
